name: Update Phonesky

on:
  push:
    branches:
      - testci
  workflow_dispatch:  # button shown only when in default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: prep download
      uses: actions/checkout@v4
      with:
        repository: AXP-OS/tools_apk_downloader
        path: dl
        
    - name: Download APK + tools
      run: |
        DL=$(cd dl && php download.php -b -p com.android.vending)
        APK="dl/${DL/;*}"
        echo "$APK"
        mkdir -p ~/.local/bin
        wget -q -O ~/.local/bin/apktool "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
        wget -q -O ~/.local/bin/apktool.jar "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar"
        chmod +x ~/.local/bin/*
        export PATH=$(pwd)/.local/bin:$PATH
        apktool --version
        echo "local_apkname=$APK" >> $GITHUB_ENV

    - name: Extract APK
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        export PATH=$(pwd)/.local/bin:$BUILD_TOOL_VERSION:$PATH
        find $BUILD_TOOL_VERSION
        DEBUG=yes APKTOOL_FLAGS=" --use-aapt2" ./patch-playstore ${{ env.local_apkname }}
        exit 2















        

        
    # https://github.com/r0adkll/sign-android-release/issues/84#issuecomment-1885690080
    - name: "Get & set app and build variables"
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
        # see: https://maven.google.com/web/index.html#com.android.tools.build:aapt2
        #wget -q -O aapt.zip https://dl.google.com/android/maven2/com/android/tools/build/aapt2/8.3.2-10880808/aapt2-8.3.2-10880808-linux.jar
        #unzip aapt.zip aapt2 && chmod +x aapt2
        #OVER=$(./aapt2 dump badging apks/OpenEUICC.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
        OVER=$(date +%F)
        [ -z "$OVER" ] && echo "ERROR: empty version detected" && exit 3
        echo "OPENEUICC_VERSION=$OVER" >> $GITHUB_ENV
        git_sha_short=$(git rev-parse --short "$GITHUB_SHA")
        echo "git_sha_short=$git_sha_short" >> $GITHUB_ENV
        echo "OpenEUICC version is: $OVER ($git_sha_short)"

    # https://github.com/r0adkll/sign-android-release
    - name: Sign apks
      id: signAPK
      uses: r0adkll/sign-android-release@master
      with:
        releaseDirectory: apks
        signingKeyBase64: ${{ secrets.APK_SIGNING_KEY_64 }}
        alias: ${{ secrets.APK_ALIAS }}
        keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.APK_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Hash release APKs (privileged + unprivileged)
      run: |
        cd apks
        sha256sum OpenEUICC-signed.apk > OpenEUICC-signed.apk.sha256
        sha256sum OpenEUICC_hidden-signed.apk > OpenEUICC_hidden-signed.apk.sha256
        sha256sum EasyEUICC-signed.apk > EasyEUICC-signed.apk.sha256  
        
    - name: Upload signed APKs
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.AXP_GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.OPENEUICC_VERSION }}"
        prerelease: false
        title: "${{ env.OPENEUICC_VERSION }} (${{ env.git_sha_short }})"
        files: |
          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk
          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk.sha256


    - name: Upload signed APKs (latest)
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.AXP_GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ env.OPENEUICC_VERSION }} (${{ env.git_sha_short }})"
        files: |
          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk
          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk.sha256
