name: Update Phonesky

on:
  push:
    branches:
      - testci
  workflow_dispatch:  # button shown only when in default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle Cache
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: prep download
      uses: actions/checkout@v4
      with:
        repository: AXP-OS/tools_apk_downloader
        path: dl
        
    - name: Build Release APK (privileged + unprivileged)
      run: |
        DL=$(cd dl && php download.php -b -p com.android.vending)
        APK="dl/${DL/;*}"
        mkdir -p ~/.local/bin
        wget -O ~/.local/bin/apktool "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
        wget -O ~/.local/bin/apktool.jar "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar"
        chmod +x ~/.local/bin/*
        export PATH=$(pwd)/.local/bin:$PATH
        apktool --version
        exit 3        
